### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/NetworkLayout.jl#11] opened 2017-05-04 16:05 UTC
ref https://github.com/JuliaPlots/PlotRecipes.jl/issues/22

**Comment by abhijithanilkumar** [comment] 2017-05-04 18:05
Duplicate of [#7](https://github.com/JuliaGraphs/NetworkLayout.jl/issues/7).

**Comment by sbromberger** [comment] 2017-05-04 21:14
...but it's apparently still happening? Do we need to tag a new version?

**Closed** 2017-05-04 21:17 UTC
